name: build docker ansible
on:
  push:
jobs:
  build:
    name: build ansible docker image
    runs-on: 	ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: build tools docker image
      run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          set -x
          version=$(cat version.txt)
          docker build -t ysicing/ansible:${version} .
          docker push ysicing/ansible:${version}
          docker logout
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
